// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Todo struct {
	ID    int    `json:"id"`
	Title string `json:"title"`
}

type TodoInput struct {
	ID    *int   `json:"id,omitempty"`
	Title string `json:"title"`
}
